# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Historical Japanese Ceramic Comparative Collection
tagline: "Historical Japanese ceramics from archaeological sites in the American West"
description: "The Historical Japanese Ceramic Comparative Collection (HJCCC) contains digital photographs and resources for identifying and describing Japanese ceramics manufactured during the Meiji and Taisho eras..."
keywords: university of idaho, HJCCC, digital collections
email: ewilliamson@uidaho.edu

# url variables
url: https://uidaholib.github.io
# url: https://www.lib.uidaho.edu
baseurl: /HJCCC_source
# baseurl: /digital/hjccc
repo-url: https://digital.lib.uidaho.edu
repo-collection-ids: HJCCC

jumbotron-image: /objects/aacc-bowls4-resized.jpg


#style with Bootswatch
bstheme: # leave blank or comment out for plain bootstrap

# Dev variables: 
# choose metadata set, i.e. easily switch between full or dev version
# be sure to also change page_gen data setting!
metadata: hjccc-objects

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'hjccc-objects'
    template: 'items'
    name: 'object-id'
    dir: 'data'
    extension: 'html'
  - data: 'hjccc-glossary'
    template: 'terms'
    name: 'slug'
    dir: 'glossary'
    extension: 'html'    
