# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Historical Japanese Ceramic Comparative Collection
tagline: "Japanese ceramics from archaeological sites in the American West"
description: "The Historical Japanese Ceramic Comparative Collection (HJCCC) contains digital photographs and resources for identifying and describing Japanese ceramics manufactured during the Meiji and Taisho eras..."
keywords: university of idaho, HJCCC, digital collections
author: evanwill # You! Add your github username
email: ewilliamson@uidaho.edu

# url variables
#url: https://uidaholib.github.io
url: https://www.lib.uidaho.edu
#baseurl: /HJCCC_source
baseurl: /digital/hjccc
# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets
# Collection's objects dir location
objects: https://www.lib.uidaho.edu/digital/objects/hjccc

repo-url: https://digital.lib.uidaho.edu
repo-collection-ids: HJCCC

jumbotron-image: /objects/aacc-bowls-4-center-crop4.jpg

# Dev variables: 
# choose metadata set, i.e. easily switch between full or dev version
# be sure to also change page_gen data setting!
metadata: hjccc_objects

# collection display variables 
# see _data/metadata-config.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'hjccc_objects'
    template: 'items'
    name: 'object-id'
    dir: 'data'
    extension: 'html'
  - data: 'hjccc_glossary'
    template: 'terms'
    name: 'slug'
    dir: 'glossary'
    extension: 'html'    

exclude: [docs, work, 'Rakefile']
